[programs.localnet]
anchor_escrow = "5m7t1HMGBkWoMgS8RKcW2J2SfYvEmYbioEMyntYd35QQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
